In [1]:
import pandas as pd
import numpy as np

import tensorflow as tf
from tensorflow import keras
from keras import Sequential 
from keras.layers import Dense

2025-03-30 11:48:06.704357: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [5]:
df = pd.DataFrame([[7, 9,8], [8, 9,5], [6, 6, 10], [12, 7, 5]], columns=['cgpa', 'resume', 'lpa'])

In [7]:
df

cgpa  resume  lpa
0     7       9    8
1     8       9    5
2     6       6   10
3    12       7    5

In [9]:
model= Sequential()

In [11]:
model.add(Dense(2, activation='linear', input_dim=2))

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [13]:
model.add(Dense(1, activation='linear'))

In [17]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [19]:
model.get_weights()

[array([[-0.10356379, -0.7931211 ],
        [-0.7034105 , -0.21585917]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.6624614 ],
        [0.17926168]], dtype=float32),
 array([0.], dtype=float32)]

In [29]:
new_weights=[np.array([[0.1, 0.1], 
                        [0.1, 0.1]], dtype=np.float32), 
             np.array([0., 0.], dtype=np.float32), 
             np.array([[0.1], 
                       [0.1]], dtype=np.float32),
             np.array([0.], dtype=np.float32)]

In [31]:
model.set_weights(new_weights)

In [33]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [35]:
optimize=keras.optimizers.Adam(learning_rate=0.01)
model.compile(loss='mean_squared_error', optimizer=optimize)

In [43]:
model.fit(df.iloc[:, 0:-1].values, df['lpa'].values, epochs=184, verbose=1, batch_size=1)

Epoch 1/184
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.1149
Epoch 2/184
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 4.8509 
Epoch 3/184
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5.3680 
Epoch 4/184
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 2.8673 
Epoch 5/184
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5.3604 
Epoch 6/184
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 3.0901 
Epoch 7/184
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 3.9275 
Epoch 8/184
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5.2469 
Epoch 9/184
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6.7777  
Epoch 10/184
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6.9112  
Epoch 11/184
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 4.0945 
Epoch 12/184
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6.5132  
Epoch 13/184
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 2.4416     
Epoch 14/184
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 4.1084 
Epoch 15/184
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 2.3922
Epoch 16/184